stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn clean
    - mvn validate
    - mvn compile
    - mvn package
  artifacts:
    paths:
      - target/*.jar  # Path to your built artifacts (e.g., JAR files)

test:
  stage: test
  script:
    - mvn test
    - mvn verify

deploy:
  stage: deploy
  needs:
    - build
    - test
  script:
    - aws s3 cp target s3://$S3_ARTIFACT/ --recursive --include "*.jar"
