stages:
  - build
  - test

before_script:
  - sudo apt update -y &&
    sudo apt install openjdk-11-jdk -y &&
    wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz &&
    sudo mv apache-maven-3.9.9-bin.tar.gz /usr/local/bin &&
    pushd /usr/local/bin &&
    sudo tar xzvf /usr/local/bin/apache-maven-3.9.9-bin.tar.gz &&
    sudo ln -fs /usr/local/bin/apache-maven-3.9.9/bin/mvn /usr/local/bin/mvn &&
    popd

# Build stage
build:
  stage: build
  script:
    - mvn clean
    - mvn validate
    - mvn compile
    - mvn package
  artifacts:
    paths:
      - target/*.jar  # Path to your built artifacts (e.g., JAR files)

# Test stage
test:
  stage: test
  script:
    - mvn test
    - mvn verify
